dvclive/metrics.py

init: introduce default path for live

---

dvclive/serialize.py
dvclive/xgb.py
setup.py

Removing unnecessary dependencies, `dvclive` in its basic installation should not have any dependencies

setup: clean up deps

---

setup.py

This will allow dvclive to be tested against dvc master

dvc: allow dvc>=2.0.0a

---

dvclive/dvc.py
dvclive/metrics.py
tests/test_main.py

Fixes #24 
Related to iterative/dvc#5466

dvc integration: get rid of dvc

---

setup.py

Tests will fail, as `dvc` `2.0.0` does not exist yet

setup: move dvc to test requirements

---

README.rst

Typo fixes in README.md

---

.github/workflows/tests.yaml

Run tests for different python versions and different machines

github actions: run tests for differnet os-es and python versions

---

dvclive/metrics.py
tests/test_main.py

Clean up summary and html files

---

dvclive/metrics.py
dvclive/utils.py
tests/test_main.py

Allow nested metrics

---

dvclive/__init__.py
dvclive/metrics.py

To match condition:
https://github.com/iterative/dvclive/blob/master/dvclive/metrics.py#L126

Update log type hints

---

tests/test_main.py

Test exception raising

---

tests/conftest.py
tests/test_keras.py

related: https://github.com/keras-team/keras/issues/3403

keras: add test

---

.github/workflows/tests.yaml
.pylintrc
README.rst
dvclive/mmcv.py
setup.py
tests/test_mmcv.py

I think that, at least for now, it makes more sense to maintain the integrations inside the `dvclive` repo in order to ensure consistency and testing without depending on opening P.R. to external repositories.
Closes #120 
Closes #110

Added MMCV integration

---

tests/test_main.py

We were missing explicit test for:
https://github.com/iterative/dvc.org/pull/2664#discussion_r677735229

Init overrides env

---

dvclive/__init__.py
tests/test_main.py

Discussed in #128 
`dvc.org` P.R: https://github.com/iterative/dvc.org/pull/2683

Removed html from public API

---

dvclive/lgbm.py
setup.py
tests/test_lgbm.py

Closes #132
PR to dvc docs: iterative/dvc.org/pull/2699

Added LightGBM 

---

dvclive/error.py
dvclive/metrics.py
tests/test_main.py

get rid of DvcLiveError calls

---

tests/test_catalyst.py

https://github.com/catalyst-team/catalyst/releases/tag/v21.11

catalyst: Update tests to latest version.

---

README.rst

1-letter commit - fix typo in README

---

dvclive/live.py
tests/test_main.py

Per https://github.com/iterative/dvclive/pull/209#discussion_r789986730

live: Raise exception if resume and not summary

---

dvclive/live.py

live: Add warning for `summary` deprecation.

---

dvclive/keras.py

Keras module is messing up with our builds. This change aims to change that. We need some further research how to handle `tensorflow`'s LazyLoader and `pylint`. Disabling everything might not be the solution we want in the long run.

pre-commit: fix keras module

---

dvclive/lightning.py
dvclive/live.py
tests/test_main.py

live: Remove `summary`

---

dvclive/live.py
tests/test_report.py

live: Set auto_open to False by default.

---

dvclive/dvc.py
dvclive/live.py
tests/test_main.py

Oversight from `live` deprecation.

Checkpoint without live

---

dvclive/lightning.py
setup.py
tests/test_lgbm.py

Closes https://github.com/iterative/dvclive/issues/234

lightning: Updates for pytorch_lightning>=1.6

---

dvclive/report.py
setup.py

project: upgrade dvc-render

---

.github/workflows/tests.yaml
tests/test_lightning.py

Per https://github.com/Lightning-AI/lightning/pull/9754

lightning: Update test.

---

README.rst

readme: remove donate badge

---

src/dvclive/data/plot.py
src/dvclive/data/scalar.py
tests/test_data/test_scalar.py

data: Don't use `with_suffix` in `output_path`.

---

.cruft.json
.github/workflows/tests.yml
.github/workflows/update-template.yaml

cruft update

---

tests/test_fastai.py

If we provide simpler task, we can save some time on tests. 
In this case, on my personal machine - from 88 s to 5 s. (I mean fastai tests)

integrations: fastai speed up tests

---

.github/workflows/tests.yml

gha: pin 3.10 to 3.10.6

---

pyproject.toml

Fixes misreported coverage introduced with #292

pyproject: fix coverage config

---

setup.cfg
src/dvclive/catalyst.py

Closes https://github.com/iterative/dvclive/issues/219

Update catalyst integration for `>22`.

---

src/dvclive/live.py
src/dvclive/report.py
tests/test_main.py
tests/test_report.py

Refactor `make_report` to accept `Live` instance as unique argument.
Closes #315

report: Add table for params

---

src/dvclive/catalyst.py
src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/keras.py
src/dvclive/lgbm.py
src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/xgb.py
tests/test_main.py
tests/test_report.py

Call `make_report` manually in the integrations.
Closes #231
Closes #103

live.set_step: Remove `make_checkpoint` and `make_report` calls.

---

setup.cfg
tests/test_fastai.py

Per https://github.com/fastai/fastai/issues/3809

fastai: Remove ProgressCallback in tests.

---

src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/report.py
src/dvclive/studio.py
src/dvclive/utils.py
tests/plots/test_image.py
tests/plots/test_metric.py
tests/plots/test_sklearn.py
tests/test_fastai.py
tests/test_huggingface.py
tests/test_keras.py
tests/test_lightning.py
tests/test_main.py
tests/test_report.py
tests/test_studio.py

`path` is ambiguous. There was also an inconsistency between the terms used: `path` for the argument and `dir` for the property.

live: Replace `path` with `dir`/`file`.

---

src/dvclive/catalyst.py
src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/keras.py
src/dvclive/lgbm.py
src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/xgb.py
tests/plots/test_metric.py
tests/test_main.py
tests/test_report.py
tests/test_studio.py

live: Rename `log` to `log_metric`.

---

src/dvclive/catalyst.py
src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/keras.py
src/dvclive/lgbm.py
src/dvclive/lightning.py
src/dvclive/xgb.py
tests/test_catalyst.py
tests/test_fastai.py
tests/test_huggingface.py
tests/test_keras.py
tests/test_lgbm.py
tests/test_lightning.py
tests/test_xgboost.py

Replace `dvclive` arg with `live`.
Rename `DvcLive` to `DVCLive`.

Revisit frameworks naming.

---

src/dvclive/live.py
src/dvclive/studio.py
tests/test_main.py

Replacing `get_step()` and `set_step()`.
Closes #172

Live: Added `step` property.

---

src/dvclive/lightning.py
tests/test_lightning.py

[bug] lightning default dir integration fix

---

tests/test_main.py

integration: dvc: test checkpoint file creation

---

src/dvclive/lightning.py
tests/test_lightning.py

`DVCLiveLogger(report=None)` was throwing an error.

lightning: support report kwarg

---

src/dvclive/dvc.py
tests/test_dvc.py

Decouple each plot type to separate entries in the `plots` section.
Closes #371

make_dvcyaml: Handle sklearn_plots properties.

---

src/dvclive/live.py
src/dvclive/plots/sklearn.py
tests/test_dvc.py

Just making it pair with saving the exp ref for now

Revert dvcyaml

---

src/dvclive/live.py
src/dvclive/studio.py
tests/test_studio.py

studio: Remove `STUDIO_REPO_URL` requirement.

---

src/dvclive/dvc.py
tests/test_dvc.py

Workaround https://github.com/iterative/dvc/issues/8689

dvc: Force posixpath format in written `dvc.yaml`.

---

src/dvclive/fastai.py
tests/test_frameworks/test_fastai.py

https://github.com/iterative/dvclive/issues/317

fastai: Log some params.

---

setup.cfg
src/dvclive/live.py
src/dvclive/studio.py
tests/test_studio.py

- Make `dvc-studio-client` a dependency

studio: Send `params` in `data` event.

---

src/dvclive/plots/metric.py

See https://github.com/iterative/dvc/issues/8817

use os line separator

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

Update pytorch_lightning.utilities.logger import.

---

setup.cfg

chore(packages): bump dvc-studio-client>=0.4.0

---

src/dvclive/live.py
tests/test_dvc.py
tests/test_studio.py

Fixes #381. This is a breaking change, so it will require a 2.0 release.

add explicit make_dvcyaml arg

---

src/dvclive/error.py
src/dvclive/lightning.py
src/dvclive/plots/base.py
tests/test_main.py

Drop DataAlreadyLogged error

---

src/dvclive/live.py
tests/test_main.py

See https://github.com/iterative/dvc.org/pull/4286/files#r1095007570

Make dvcyaml explicit

---

src/dvclive/utils.py
tests/test_utils.py

lightning: more robust metric name standardization

---

src/dvclive/live.py
tests/test_dvc.py

Need to pass a list after https://github.com/iterative/dvc/pull/9064
Closes #486

save_dvc_exp: fix `include_untracked`

---

src/dvclive/live.py
src/dvclive/plots/metric.py
src/dvclive/utils.py

Pointless refactor 😄 based on https://github.com/iterative/dvc/pull/9148#discussion_r1132111685.

replaces utils functions with funcy

---

setup.cfg
src/dvclive/optuna.py
tests/test_frameworks/test_optuna.py

Added Optuna callback.

---

src/dvclive/dvc.py
tests/test_dvc.py

Found debugging https://github.com/iterative/example-repos-dev/pull/191#issuecomment-1492252216

make_dvcyaml: Include `metrics` section also if `live.summary`.

---

src/dvclive/live.py
tests/test_dvc.py

Instead of tracking the entire `live.dir`, only git add paths that match `self.dir` and:
- Are  currently untracked (in self._dvc_repo.scm.untracked_files())
- Don't match any `self._dvc_repo.index.outs`.
Closes #516

live: Be more conservative when git adding paths inside `dvc exp run`.

---

README.md
examples/DVCLive-Quickstart.ipynb

To be used in Colab
Test in:
https://colab.research.google.com/github/iterative/dvclive/blob/colab/examples/DVCLive-Quickstart.ipynb

Add DVCLive-Quickstart

---

setup.cfg
src/dvclive/live.py
tests/conftest.py
tests/test_studio.py

Per https://github.com/iterative/dvc-studio-client/pull/28

studio: Support `DVC_` env vars.

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_log_artifact.py

Support `artifacts` section

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_dvc.py
tests/test_main.py

It seems like printing out a stage template is causing more annoyance and confusion than help. Fixes #509. See also:
* #536
* https://discord.com/channels/485586884165107732/1098954552927059978/1098976007257591868

revert get_dvc_stage_template

---

src/dvclive/plots/image.py
tests/plots/test_image.py

Fixes #412. Trying to close some user requests.

allow for custom image subclasses

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml

chore(lint): don't apply mdformat to PR templates

---

src/dvclive/studio.py
tests/test_studio.py

studio: send images.

---

src/dvclive/serialize.py

fix(summary): proper EOF with a newline

---

setup.cfg
tests/test_studio.py

https://github.com/iterative/dvc-studio-client/releases/tag/0.10.0

deps: bump dvc-studio-client>=0.10.0,<1

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

lightning: Only force init if report="notebook".

---

pyproject.toml
src/dvclive/lightning.py

Closes https://github.com/iterative/dvclive/issues/596

lightning: Update imports and bump requirements

---

src/dvclive/live.py
tests/test_main.py

add cache_images arg

---

src/dvclive/keras.py
tests/test_frameworks/test_keras.py

Trying to fix failure in https://github.com/iterative/dvclive/actions/runs/5468302728/jobs/9955750376?pr=620

fix(tests): Update imports in keras

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

Lightning model

---

.gitignore

Not sure what's generating these files, but I'm finding I frequently have to ignore them

ignore version file

---

src/dvclive/live.py

Addresses https://github.com/iterative/dvclive/pull/631/files#r1279155281

wrap cache warnings to suppress errors

---

README.md
examples/DVCLive-PyTorch-Lightning.ipynb
examples/DVCLive-Quickstart.ipynb
examples/DVCLive-YOLO.ipynb

Update other examples for consistency.
Also https://github.com/iterative/dvc.org/pull/4742
Closes #603

Add DVCLive-YOLO notebook.

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_dvc.py

Proposed implementation for https://github.com/iterative/dvclive/issues/456#issuecomment-1665813858.

dvcyaml: warn if tracked as stage output

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_log_artifact.py

- Add type hints.
- Simplify if/else warnings in cache

dvc: Extract `find_overlapping_stage`.

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_main.py

Leftover when upgrading to DVC 3.0

dvc: Drop checkpoint.

---

src/dvclive/live.py

I think leaving this out was unintentional @dberenbaum ?

live.logger: Honor DVCLIVE_LOGLEVEL env var

---

src/dvclive/dvc.py
src/dvclive/live.py
src/dvclive/utils.py
tests/test_dvc.py
tests/test_log_artifact.py

dvc: Extract `ensure_dir_is_tracked` to `dvc`.

utils: Add catch_and_warn.

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

lightning: support list params

---

pyproject.toml
tests/test_studio.py

- Refactor to simplify asserts.
- Bump "dvc-studio-client>=0.15.0,<1"

tests: Update studio tests with latest release.

---

examples/DVCLive-HuggingFace.ipynb

Follow-up to #697. Just a few minor style edits.

minor style edits to hf example notebook

---

README.md

guide.
The previous link led to a 404 when accessing the example notebook.

Fix typo in sklearn notebook link

---

pyproject.toml

guide.
-----
Bumping the min version of DVC now the `dvc_objects` `umask` error has been fixed.

Update min version of DVC to 3.33.3

---

noxfile.py
pyproject.toml

Adding back nox per https://github.com/iterative/dvclive/pull/749#issuecomment-1857226519. Looks like it was removed in https://github.com/iterative/dvclive/pull/527 without too much thought beyond one user running into an issue with it.

add back nox

---

README.md

Fix a typo in README example 

---

.gitignore

ignore logs from vscode and pycharm

---

.github/PULL_REQUEST_TEMPLATE.md

fix PR template

---

src/dvclive/live.py

https://github.com/iterative/dvclive/pull/702#issuecomment-2103287805

consolidate repro warnings

---

src/dvclive/huggingface.py
tests/frameworks/test_huggingface.py

fix(hf): pass fake eval dataset since it is required

---

pyproject.toml
src/dvclive/plots/sklearn.py
tests/frameworks/test_huggingface.py
tests/plots/test_sklearn.py

Fixes https://github.com/iterative/dvc/issues/10782
----------------

fix(sklearn): probas_pred got removed since 1.7

---

.pre-commit-config.yaml
pyproject.toml
src/dvclive/fabric.py
src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/studio.py
src/dvclive/utils.py
tests/conftest.py

linters: bump mypy and ruff
