iterative/dvclive

dvclive/__init__.py
tests/test_main.py

init: default path if no init called

---

dvclive/keras.py
dvclive/serialize.py

json: use indent

---

README.rst

There is not an easy way to find the docs page from the repository.

Add link to `dvc.org/doc/dvclive`

---

dvclive/metrics.py
tests/test_main.py

Changes:
- Added `.dvclive.tsv` prefix to *metrics logs* files. Does not affect visualizations with `dvc plots` or the HTML report.
- Replaced `shutil.rmdir` with `rglob`+`unlink()` to prevent unintentional deletions of user files.
Closes #102

Safer cleanup

---

dvclive/__init__.py
dvclive/error.py
dvclive/metrics.py
tests/test_main.py

Fixes #60 
TODO
~~- [x] - allow overriding if proper env variable is present~~
~~- [x] - If same dir is provided via env, make sure to update config~~
EDIT:
we agreed in #74 to throw on configuration mismatch

init: throw on dvc/dvclive config mismatch

---

.github/workflows/tests.yaml

Add verbose option to the test build so that we can get more info on failed builds.

build: tests: make tests run verbose

---

dvclive/metrics.py
tests/test_main.py

Improve conditional expression checking  step param value.
Closes #129

Fix step param in dvclive.log method 

---

dvclive/xgb.py
tests/test_xgboost.py

Extend the existing XGBoost integration (dvc.xgb) to include model saving functionality. 
Closes #109

Add saving model in XGBoost

---

dvclive/metrics.py
tests/test_main.py

`dvc.org` PR: https://github.com/iterative/dvc.org/pull/2783
Close #148

Updated html_path

---

dvclive/metrics.py
dvclive/utils.py
tests/test_main.py

Subsequent calls of `dvclive.log()` using a nested metric name (i.e. `"train/foo"`) were not triggering `next_step`

Fixed infer `next_step` for nested metric

---

.github/release-drafter.yml

Added release-drafter.yml

---

dvclive/lightning.py
setup.py
tests/test_lightning.py

Close #85 
- Added callback for pytorch lightning
- Didn't update docs. I'll do it when you accept my changes. It's my first PR, so I'm not sure, that I'm doing it right ¯\_(ツ)_/¯

Add new callback to DVCLive

---

tests/test_lightning.py

Latest version (v1.5.0) requires to override all dataloader methods: PyTorchLightning/pytorch-lightning#9161 making pylint raise error in our test
Close #186

lightning: Override all dataloader methods

---

tests/test_catalyst.py

Recent catalyst versions changed the default formatting of the metrics, based on topk argument: https://github.com/catalyst-team/catalyst/pull/1330
Close #184

catalyst: Update accuracy check

---

dvclive/live.py
dvclive/utils.py
tests/test_main.py

The default `dict.update` method only update the 1st level key of the
dict. When using metric with with 2 or more nested levels, only the
last update of each nested key will be kept.
For example:
>> summary_data = {'valid': {'accuracy': 0.6}}
>> summary = {'valid': {'precision': 0.5}}
>> summary_data.update(summary)
>>> summary_data
{'valid': {'precision': 0.5}}
The function `update_nesteddict` will correctly update an arbitrarily
nested dict, so that:
>> summary_data = {'valid': {'accuracy': 0.6}}
>> summary = {'valid': {'precision': 0.5}}
>> summary_data = update_nesteddict(summary)
>>> summary_data
{'valid': {'precision': 0.5, 'accuracy': 0.6}}
Fixes #196 

update metric summary data of arbitrary depth

---

tests/test_mmcv.py

The MMCV team prefers to keep the integration in the mmcv repo. This P.R. adds tests that directly use the DVCLive logger of the mmcv repo.
Pending on https://github.com/open-mmlab/mmcv/pull/1208 to get merged

Added test_mmcv

---

setup.py

For `catalyst==22.02` our builds fail, need to investigate that, restricting the version for now.
Temporary workaround for #219

catalyst: restrict version

---

dvclive/data/plot.py
dvclive/dvc.py
dvclive/live.py
dvclive/report.py
dvclive/utils.py
setup.py
tests/conftest.py
tests/test_main.py
tests/test_report.py

- Uses `dvc_render`.
- Add new method `Live.make_report` that users can call from a `Live` instance at any point. 
This method is still called by default on `next_step` if the report has been enabled. I'm not sure about preserving that behavior and would move towards explicit `make_report` calls.
- Add new entry point `dvclive-show` that can generate the latest HTML report.
Defaults to the previous behavior, for now. `html` report only gets generated if enabled on the `dvc.yaml` side . However, users can manually enable `html` without DVC by passing:
```python
live = Live(report="html")
```
Closes #213 #195

live: `html` report without DVC.

---

dvclive/live.py
tests/test_main.py

Store report in the old path when users use `live` section in DVC.

live: backward compatible html_path

---

dvclive/fastai.py
dvclive/huggingface.py
dvclive/keras.py
dvclive/lightning.py
dvclive/utils.py
tests/test_fastai.py
tests/test_huggingface.py
tests/test_keras.py
tests/test_lightning.py

This attempts to standardize outputs across frameworks using a format that is more convenient for our UIs (Studio, VScode)
Pytorch Lightning example:
- Before
- After

integrations: Standardize metric name to group under subfolders.

---

dvclive/live.py
dvclive/report.py
dvclive/utils.py
tests/conftest.py
tests/test_main.py
tests/test_report.py

Depends on https://github.com/iterative/dvc-render/pull/69
Closes #91 
The new default value for `report` is `auto`. 
If `CI` env var is set, use `md` else use `html`.
```python
import random
import time
from PIL import Image
from PIL import ImageDraw 
live = Live(report="md")
for i in range(2):
live.log("foo", i + random.random())
live.log("bar", i + random.random())
img = Image.new("RGB", (50, 50), (255, 255, 255))
draw = ImageDraw.Draw(img)
draw.text((20, 20), f"{i  + random.random():.1f}", (0,0,0))
live.log_image("img.png", img)
live.next_step()
time.sleep(5)
```

report: Introduce `markdown` support.

---

.github/workflows/package.yaml

See https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-.
> The master branch version has been sunset. Please, change the GitHub Action version you use from master to release/v1 or use an exact tag, or a full Git commit SHA.
Also drops `__token__`, which does not need to be specified as it's the default.

[skip ci]: use pypa/gh-action-pypi-publish@release/v1

---

pyproject.toml
setup.cfg
src/dvclive/error.py
src/dvclive/live.py
src/dvclive/serialize.py
tests/test_main.py

Provides two new methods which log parameters to a yaml file (`params.yaml`):
- `log_param(name, value)` logs the given parameter name/value
- `log_params(params)` logs the given set of parameters (dict).

add log_param/log_params

---

src/dvclive/live.py

- live: get rid of \_params_path
- live: update ParamLike to include lists

cleanup log param

---

src/dvclive/keras.py
tests/test_keras.py

Suggestion. If we decide it's good I can try to add it to all other integrations.
It makes this workflow (non obvious, not natural, less scalable, and not documented?): 
```python
logger = DvcLiveCallback(path="evaluation", report=None)
live = logger.dvclive
```
into:
```python
live = Live("evaluation", report=None)
.... DvcLiveCallback(dvclive = live)
```
- We need an ability to pass live logger instance or params, otherwise callback would initialize its own instance and will be producing reports for example, would ignore path, etc, etc
- It's better to pass live to callbacks (vs asking callback to give us logger): proper order of control (code looks natural, easier to test), one `live` instance could be shared across multiple callbacks, etc

keras: add ability to pass live into callback

---

src/dvclive/error.py
src/dvclive/live.py
tests/test_main.py

As discussed in https://github.com/iterative/dvc.org/pull/3994#discussion_r983594345

live: get rid of ParameterAlreadyLoggedError

---

src/dvclive/catalyst.py
src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/lgbm.py
src/dvclive/xgb.py
tests/test_catalyst.py
tests/test_fastai.py
tests/test_huggingface.py
tests/test_keras.py
tests/test_lgbm.py
tests/test_xgboost.py

https://github.com/iterative/dvclive/pull/302 followup to do the same for other loggers
+ it simplifies the Keras test
Next steps:
- MMCV requires a separate PR in their repo
- Lighting logger looks very different from the others + some cleanup can be done. But it already has a way to pass a live instance via `experiment` parameter
- Update docs

Add ability to pass logger instance to frameworks

---

src/dvclive/huggingface.py
tests/test_huggingface.py

Use simple dataset and model from `transformers/tests/trainer`.

tests: Simplify huggingface tests.

---

src/dvclive/data/sklearn_plot.py
src/dvclive/live.py
tests/test_data/test_plot.py

Rename the existing `name` argument to `kind`. This argument is used to determine the type of plot. Add a new optional `name` argument to define the output file.
Closes #323

log_sklearn_plot: Support custom name.

---

src/dvclive/catalyst.py
src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/keras.py
src/dvclive/lgbm.py
src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/studio.py
src/dvclive/xgb.py
tests/test_main.py

`log_metric` now stores logged value in `live.summary` but doesn't call `make_summary` as before.
Closes #238
Closes #232

live: Moved all `make_{x}` to `next_step()`.

---

src/dvclive/live.py
tests/test_main.py

live: Add `__enter__` and `__exit__`.

---

src/dvclive/report.py
tests/test_report.py

report: Handle custom names used in `sklearn_plots`.

---

src/dvclive/fastai.py
tests/test_fastai.py

Found some bugs while working on https://github.com/iterative/dvc-get-started-cv/pull/59 .
- Use the occasion to also remove the redundant logging of `epoch` as a metric.
- Expose `with_opt` option.
- Don't increase the step when resuming.

fast.ai: Handle resuming.

---

src/dvclive/live.py
tests/test_dvc.py

Separate DVCLive only execution from `dvc repro` execution.
Don't save experiment inside `dvc repro` execution.

_init_dvc: Skip experiment save if inside repo has stages.

---

src/dvclive/lightning.py
tests/test_lightning.py

Lightning was recording one step per logging iteration, but by default that logs every 50 steps (https://pytorch-lightning.readthedocs.io/en/stable/extensions/logging.html#logging-frequency). This leaves you with 3 different values between epoch, lightning step, and dvclive step.

lightning: record actual training step

---

src/dvclive/live.py
tests/test_fastai.py
tests/test_lightning.py
tests/test_main.py

Add `update_step` option to `make_summary`, default `True` to preserve old behavior but set to `False` inside `live.end`.
Closes #389

live.end: Don't increment `step` value.

---

src/dvclive/live.py
src/dvclive/plots/sklearn.py
tests/test_report.py

Currently breaks when using `.json` in the `name` because `live._plots` keeps the suffix.

log_sklearn_plot: fix .json replacement

---

src/dvclive/dvc.py
src/dvclive/live.py
tests/test_main.py

----
There was a behaviour change shipped in the VS Code extension a few days ago where we no longer auto-select experiments for plotting by default. We (I) changed the behaviour to only auto-select experiments that have been run inside of the current session. Otherwise, we leave the selection up to the user (and/or the previous session). In order to do this I changed the extension's internal mechanics to rely on the `executor` & `status` fields inside of the `exp show` data. These fields are not populated when DVCLive is running outside of the experiment context and using `exp save` to generate the final experiment data (I've looked at the code and can see this would be a difficult change). 
All of that leads …

Create signal file whenever DVCLive is running a non-DVC experiment (VS Code)

---

src/dvclive/live.py
tests/test_dvc.py
tests/test_studio.py

`dvc repro` execution was not correctly getting `baseline_rev`, breaking Live metrics remote scenario

studio: Fix passing `rev` in `dvc repro` execution.

---

src/dvclive/dvc.py
src/dvclive/live.py

Only log warnings about Studio if `studio_token` is set. Only log warnings about DVC Repo if `save_dvc_exp` is True.

live: Don't log unnecessary warnings.

---

src/dvclive/studio.py

In CI scenarios the previous logic was not reliable. Feels reasonable to just use this simpler logic as default for all scenarios.

studio: Use `ls-remote --get-url` as default.

---

src/dvclive/live.py
tests/test_dvc.py

Fix check to detect `dvc repro` execution to take in account `.dvc` files. 
Pass `force=True` to `experiments.save` to prevent failure and ensure `dvc commit` of those files (in CLI usage, dvc prompts for confirmation instead of failing).

dvc: Don't ignore `save_dvc_exp` if there are `.dvc` files.

---

src/dvclive/live.py
tests/test_studio.py

When `_inside_dvc_exp` (user running `dvc exp run`), we were incorrectly trying to send the `data` event if `STUDIO_TOKEN` wasn't set, logging unnecessary warnings.

studio: Skip `data` event if no `STUDIO_TOKEN`.

---

src/dvclive/studio.py
tests/test_studio.py

When plots are defined in `{live.dvc_file}`, there was a mismatch between the names returned by `repo.plots.show` and the names sent to the live endpoint.
Closes https://github.com/iterative/studio/issues/4981
--- 
Tested in the repo mentioned in the issue:
https://user-images.githubusercontent.com/12677733/215758399-1c0b87b0-334a-47d7-89f5-4bf0e219e1f2.mov

studio: Include `{live.dvc_file}::` prefix when needed.

---

src/dvclive/live.py
tests/test_main.py

Add `live._inside_with` boolean to handle it.
The idea is to include additional data in an experiment when using frameworks:
```python
from dvclive.keras import DVCLiveCallback
with Live(save_dvc_exp=True) as live:
live.log_param("foo", 2)
model.fit(
x, y,
callbacks=[DVCLiveCallback(live=live)])
live.summary["out-of-loop-metric"] = 1
```

live: Skip `live.end` calls inside context manager.

---

src/dvclive/plots/metric.py
src/dvclive/report.py
src/dvclive/utils.py
tests/test_main.py

This is another breaking change, so it would be good to merge it along with #443, although it doesn't need to block if it's not quick to get merged.
This shortens repetitive plots fields. For example, instead of `results/plots/metrics/train/epoch/acc.tsv: train/epoch/acc`, it becomes `results/plots/metrics/train/epoch/acc.tsv: acc`.

Shorten names of fields in plots tsv files

---

src/dvclive/live.py

Until we address https://github.com/iterative/dvclive/issues/381 (needs a major version change), we can stop removing `dvc.yaml` during init. That way, for people who transition to using pipelines, they still keep their `dvc.yaml` from the no-pipeline runs. Should at least partially address https://github.com/iterative/dvclive/issues/435.

don't remove dvc.yaml file

---

src/dvclive/report.py
src/dvclive/utils.py
tests/test_report.py
tests/test_studio.py

metrics: preserve the name stored in the `.tsv`.

---

src/dvclive/live.py
tests/test_dvc.py

@daavoo @shcheklein I messed up the release 🤦 . I was so focused on the `dvc.yaml` changes that I forgot we also need to update `save_dvc_exp` to work when there's an existing pipeline.
There's an open question of whether it should work with `dvc repro`. In the interest of being simple and explicit, I went with saving an experiment even during `dvc repro`. In other words, the only time saving an experiment gets skipped is inside `dvc exp run`.

`save_dvc_exp` works with existing pipelines/repro

---

setup.cfg
src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

This PR introduces a the `dvcyaml: bool = True,` kwarg for the DVCLiveLogger for Pytorch Lightning following the addition of the same kwarg to the Live logger class in [PR 443](https://github.com/iterative/dvclive/pull/443).  Tests were updated accordingly 
I did not update documentation because it is already out of date.  
This PR also adds `py` as a dependency since it is no longer an explicit dependency of pytest. 

Introduce  `dvcyaml: bool = True`  kwarg for DVCLiveLogger

---

setup.cfg
src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/report.py
src/dvclive/utils.py
tests/test_report.py

Renders existing HTML report inside an IFrame and updates it on each next_step.
Closes #309
---
https://user-images.githubusercontent.com/12677733/217227396-5ea5f552-bd9c-460a-8ebb-66892a969413.mp4

report: Add `notebook` mode.

---

setup.cfg
src/dvclive/report.py
src/dvclive/utils.py

Requires https://github.com/iterative/dvc-render/pull/118
Closes #460

report: Use `HTML` instead of `IFrame` inside Google Colab.

---

src/dvclive/live.py
tests/test_dvc.py

live: Ignore `DvcException` in `save_dvc_exp`.

---

src/dvclive/dvc.py
tests/test_dvc.py

Plots in `dvclive/plots/metrics` do not use the `step` value stored in the tsv but instead infer a step value that's a simple counter of the row numbers. This PR configures those plots to use the `step` value from the tsv as the `x` axis.
Example using the lightning callback, which logs every 50 train steps by default:
Before this PR:
After this PR:

Add step to plots config

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

Only call next_step for
- `update_train_step_metrics`
- `update_train_epoch_metrics`
- `log_eval_end_metrics`
Prevents calling next_step when external callbacks call `log_metrics` or during the multiple `update_eval_step_metrics`.
Closes #477

lightning: Determine when to call next_step based on `inspect.stack`.

---

setup.cfg
src/dvclive/dvc.py
src/dvclive/live.py
tests/test_studio.py

To unbreak to live-experiments, see https://github.com/iterative/studio/issues/5259 for context

Require DVC >2.45.1

---

src/dvclive/utils.py
tests/test_utils.py

If a metric didn't contain `split` but only `freq` suffix, `standardize_metric_name` was causing a conflict in the summary. For example: `grad_step` was being stored as `step/grade`.

lightning: prevent conflict with internal `step` property.

---

src/dvclive/error.py
src/dvclive/live.py
tests/conftest.py
tests/test_dvc.py
tests/test_log_artifact.py

fix: #378
---
```python
import time
from pathlib import Path
Path("data").write_text(str(time.time()))
with Live(save_dvc_exp=True) as live:
live.log_artifact("data")
```
```console
$ git init
$ dvc init
$ git add train.py
$ git commit -m "init"
$ python train.py
$ git show 6d1a79f
commit 6d1a79fa891e3582a6a9ef93f4e826e5eee5bbe4 (refs/exps/ad/10dbdb6aa0c13b73f48ed8416a65dd57d94899/duddy-yews)
Author: David de la Iglesia Castro <daviddelaiglesiacastro@gmail.com>
Date:   Mon Feb 20 15:23:14 2023 +0100
dvc: commit experiment duddy-yews
diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..3af0ccb
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1 @@
+/data
diff --git a/data.dvc b/data.dvc
new file mode 100644
index 0000000..3088b76
--- /dev/null
+++ …
```

Implement log_artifact method for live

---

src/dvclive/live.py
src/dvclive/studio.py
tests/conftest.py
tests/test_frameworks/test_lightning.py
tests/test_studio.py

Closes #501
Tested manually against Studio prod with DVCLive only and `dvc exp run`:
https://studio.iterative.ai/user/daavoo/projects/test-dvclive-studio-subdir-tig1qeggo8?panels=plots%2C&commits=6846546%2Cprimary%3B853%2Cpurple%3B850%2Cred%3B6846392%2Cgreen
Also tested setting a custom project dir during Studio import:
https://studio.iterative.ai/user/daavoo/projects/subdir-mtf4f648wn?panels=plots%2C&commits=850%2Cprimary%3B853%2Cpurple%3B6846634%2Cred%3B6846632%2Cgreen

studio: Send paths relative to `self._dvc_repo.root_dir`.

---

src/dvclive/dvc.py
src/dvclive/live.py
src/dvclive/serialize.py
tests/test_dvc.py
tests/test_main.py

Closes #468.
Logs output during `Live.end()` like:
```
INFO:dvclive:To run with DVC, add this to /Users/dave/Code/lstm_seq2seq/dvc.yaml:
stages:
dvclive:
cmd: <python my_code_file.py my_args>
deps:
- <my_code_file.py>
outs:
- dvclive/params.yaml:
cache: false
- dvclive/metrics.json:
cache: false
- dvclive/plots:
cache: false
- model
```

log stage template

---

src/dvclive/fastai.py
src/dvclive/huggingface.py
src/dvclive/keras.py
tests/test_frameworks/test_fastai.py
tests/test_frameworks/test_huggingface.py
tests/test_frameworks/test_keras.py

Tested with setup in https://github.com/iterative/example-get-started-experiments/
```py
from fastai.callback.tracker import SaveModelCallback
train_arch = 'resnet18'
for base_lr in [0.1, 0.01, 0.001]:
with Live(dir=os.path.join('results', 'train'), save_dvc_exp=True) as live:
learn = unet_learner(
data_loader, arch=getattr(models, train_arch), metrics=DiceMulti, 
path="results")
fine_tune_args = {
'epochs': 2,
'base_lr': base_lr
}
live.log_params(fine_tune_args)
learn.fine_tune(
**fine_tune_args,
cbs=[DVCLiveCallback(live=live), SaveModelCallback()])
```
And then retrieving the best model with:
```
!dvc exp show --csv > results.csv
```
```py
import dvc.api
import pandas as pd
results = pd.read_csv("results.csv")
best_exp = …
```

frameworks: Use `log_artifact`.

---

src/dvclive/live.py
tests/test_dvc.py
tests/test_frameworks/test_lightning.py
tests/test_studio.py

Requires using either `dvc exp run` or `save_dvc_exp=True`.
Closes https://github.com/iterative/dvclive/issues/474

live: Explicitly require `exp` for sending Studio updates.

---

src/dvclive/live.py
tests/test_dvc.py

Closes #510
```bash
git init repo
cd repo
dvc init
git add .
git commit -m "setup"
echo "from random import random
NUM_EPOCHS = 2
with Live(save_dvc_exp=True) as live:
live.log_param('epochs', NUM_EPOCHS)
for epoch in range(NUM_EPOCHS):
live.log_metric('metric_name1', random())
live.next_step()" > train.py
echo "stages:
train:
cmd: python train.py" > dvc.yaml
dvc exp run
dvc exp show
```
```
──────────────────────────────────────────────────────────────────── 
Experiment                 Created    metric_name1   step   epochs  
──────────────────────────────────────────────────────────────────── 
workspace                  -               0.92207      1   2       
master                     04:37 PM              -      -   -       
└── a65edf1 [unfit-code]   04:37 …
```

live: Track `self._dir` when `self._inside_dvc_exp`.

---

src/dvclive/live.py
src/dvclive/plots/image.py
tests/plots/test_image.py

Log image from an existing file. Helps to convert a repo like YOLO where images are produced already by some core code and we need to capture and transfer them into the DVCLive output dir.
It also adds some test for `log_image`.
Related: https://github.com/shcheklein/ultralytics
Related: https://github.com/ultralytics/ultralytics/issues/1909
Docs https://github.com/iterative/dvc.org/pull/4463
-------

Support path to an image in `log_image`

---

README.rst

There were a few links to update. One of them was 404ing. It means we are missing a redirect to the API reference in the docs? (cc @daavoo )
-------

fix(readme): broken links for docs

---

src/dvclive/live.py
tests/conftest.py
tests/test_studio.py

To ensure `experiment_rev` is sent.
Found that it was the underlying issue of https://github.com/iterative/studio/issues/5673#issuecomment-1508480082. I thought Studio relied on `baseline_sha`, `exp_name` pair to match live experiments with experiment ref.
Regardless, this was a plain bug that had to be fixed and went under the radar.

studio: Save experiment before posting `done` event.

---

src/dvclive/live.py
src/dvclive/plots/sklearn.py
src/dvclive/report.py
tests/test_dvc.py
tests/test_report.py

Adds an option to normalize confusion matrix like this:
```python
live.log_sklearn_plot(
"confusion_matrix",
[0, 0, 1, 1],
[0, 1, 1, 0],
name="confusion_matrix_normalized",
normalized=True,
)
```
Quite handy to see a better heat map in case of classes being highly misbalanced.
-----------
guide.
- ⌛  [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in
[dvc.org](https://github.com/iterative/dvc.org) and linked it here.

feat(sklplots): add confusion matrix normalized option

---

src/dvclive/dvc.py
src/dvclive/live.py
src/dvclive/plots/__init__.py
src/dvclive/plots/custom.py
src/dvclive/plots/sklearn.py
src/dvclive/report.py
tests/plots/test_custom.py
tests/plots/test_sklearn.py
tests/test_report.py

Create DVC plots from datapoints (list of dictionaries) and plot config.
Closes #271
Closes #453
```py
datapoints = [{"foo": 1, "bar": 2}, {"foo": 3, "bar": 4}]
with Live() as live:
live.log_plot("foo_default", datapoints, x="foo", y="bar", title="Default Linear Plot")
live.log_plot(
"foo_scatter",
datapoints,
x="foo",
y="bar",
template="scatter",
title="Plot using Scatter template",
y_label="CUSTOM LABEL: BAR",
x_label="CUSTOM LABEL: FOO"
)
```
Example output:
- `dvclive/plots/custom/foo_default.json`
```json
[
{
"foo": 1,
"bar": 2
},
{
"foo": 3,
"bar": 4
}
]                                                               
```
- `dvclive/dvc.yaml`
```yaml
plots:
- plots/custom/foo_default.json:
x: foo
y: bar
title: Default Linear Plot
- plots/custom/foo_scatter.json:
template: scatter
x: …
```

live: Add `log_plot`.

---

src/dvclive/live.py
tests/test_dvc.py

live: Catch errors in `_ensure_paths_are_tracked_in_dvc_exp`.

---

src/dvclive/dvc.py
tests/test_log_artifact.py

Found this while iterating on the #559 
It was logging path name as:
```python
{'artifacts': {'model': {'path': '../.dvc/cache/d4/1d8cd98f00b204e9800998ecf8427e', 'type': 'model'}}}
```
---------
guide.

fix(log_artifact): don't follow symlink on dumping dvc.yaml

---

src/dvclive/live.py
src/dvclive/utils.py
tests/test_log_artifact.py

Closes #550
```python
with Live() as live:
live.log_artifact("model.pth", copy=True)
```
It copies a file into `dvclive/artifacts/model.pth` and tracks it with DVC in a regular way.
---------
TODO (when accepted):
[dvc.org](https://github.com/iterative/dvc.org) and linked it here.

feat(log_artifact): add an option to copy (capture) into dvclive dir

---

setup.cfg
src/dvclive/live.py
src/dvclive/report.py
tests/test_report.py

Fixes #537 and #546
Depends on https://github.com/iterative/dvc-render/pull/129.
https://user-images.githubusercontent.com/2308172/236560495-15c517fc-1456-4f6f-accb-2263c2f0dc01.mov
Still needs:

use markdown for notebook reports

---

src/dvclive/dvc.py
tests/test_dvc.py
tests/test_log_artifact.py

Fixes code like this:
```python
with Live() as live:
for _ in range(3):
live.log_artifact("model.pth", type="model")
live.next_step()
```
Here `make_dvcyaml` is called twice in a row at the end. Previous it was causing artifacts paths to be modified each time (adding a relative level of `..`).
-----------
guide.

fix(make_dvcyaml): make it idempotent for artifacts

---

setup.cfg
src/dvclive/live.py
tests/test_dvc.py
tests/test_log_artifact.py
tests/test_studio.py

Use it in the `start` event of post_live_metrics and `experiments.save`.
Closes https://github.com/iterative/dvclive/issues/557
https://github.com/iterative/dvclive/assets/12677733/d7d8ef37-3843-4d7e-aa4c-140443bc7637

live: Add `exp_message` arg.

---

CONTRIBUTING.rst

I've updated the contributing guide to instruct a contributor to install also the `dev` extra. Otherwise, `pytest` and all other development dependencies won't be available.
guide.

docs: add `dev` extra to install command in contributing guide

---

src/dvclive/lgbm.py
tests/test_frameworks/test_lgbm.py

Using multiple "eval_sets" would result in many points being logged on the same graph of dvc. I extended the DVCLiveCallback class locally and changed the __call__ definition to support logging for different eval_sets in different graphs.
guide.

support metrics from multiple eval sets in lgbm

---

tests/test_log_artifact.py

Regression test for a bug reported by @aguschin which was fixed (I don't know if intentionally or not) by @dberenbaum in #605

Add test_log_artifact_type_model_when_dvc_add_fails

---

src/dvclive/live.py
tests/test_main.py

cleanup dvcyaml

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

Adds `dvclive.lightning.DVCLiveLogger(cache_images=True)`

add cache_images to lightning

---

src/dvclive/lightning.py

add back old pytorch_lightning imports

---

README.md

guide.
As discussed in an issues in [studio#6422](https://github.com/iterative/studio/issues/6422)) (private repo) - suggested some changes to this snippet:
copy-pasting motivation:
> Yes - a working snippet is what I was driving it.
> Looking at the snippet in the readme I suggest to consider updating maybe - that's why I looked at some competitors and compiled a new one before.
> 
> first order problem IMO is having a snippet that works out of the box
> 2nd order problem - polish how this snippet looks  - so it's short and clean and nice, but also interesting.
> things that bother me today a bit about the snippet from the [readme](https://github.com/iterative/dvclive/tree/main#example-code)(⚠️ : opinionated / …

README: A more engaging code snippet ecample

---

src/dvclive/lightning.py
tests/test_frameworks/test_lightning.py

Update per https://github.com/iterative/dvclive/pull/649#discussion_r1285904791. @daavoo I think this is all we need for consistency with huggingface for now. WDYT?

lightning: copy best model

---

examples/DVCLive-HuggingFace.ipynb
src/dvclive/huggingface.py
tests/test_frameworks/test_huggingface.py

- Log `Trainer.args`.
- Add `log_model` argument.
Every framework does its own thing. No strong opinions but I went with the following:
- If `None` (default) will not log any artifact.
- If `all` will call log_artifact with `output_dir` at each `on_save` call.
- If `True` will save the model `on_train_end` and call `log_artifact` with type=model and copy=True.
Will use `best` as name if `args.load_best_model_at_end` else `last`.
- Add Notebook/Colab example
Closes #641 
---
TODO:

HuggingFace improvements

---

src/dvclive/live.py
tests/test_log_artifact.py

Per https://github.com/iterative/dvclive/pull/631#discussion_r1293624243

cache: cache in dvc exp if not stage output

---

src/dvclive/live.py
src/dvclive/plots/metric.py
src/dvclive/studio.py
tests/test_log_metric.py
tests/test_main.py

- Support string metrics (forgot to support them when DVC added support)
- Don't recast to float when sending to Studio.
Closes https://github.com/iterative/studio-support/issues/93
I have manually tested end to end against Studio sending inf/nan from `math`, `numpy`, and `torch`. 
The Vega plots in the frontend appear to handle just fine datapoints with those values (the datapoint is skipped).

live.log_metric: Cast `nan` and `inf` to string.

---

src/dvclive/live.py
tests/test_log_artifact.py

Context: https://iterativeai.slack.com/archives/CB41NAL8H/p1693333001773389
tldr `log_artifact` is a noop without a DVC repo, so we should warn in this scenario.

warn on log_artifact when no repo

---

pyproject.toml

guide.
---
Minor: gets rid of warnings of the form 
```
tests/test_studio.py:197
/dvclive/tests/test_studio.py:197: PytestUnknownMarkWarning: Unknown pytest.mark.studio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.studio()
```
from the `pytest` logs.

pyproject: add custom pytest markers definition

---

tests/test_dvc.py
tests/test_main.py
tests/test_report.py
tests/test_vscode.py

guide.
-----
Fixes issue of the format:
```
/dvclive/tests/test_dvc.py:160: PytestMockWarning: Mocks returned by pytest-mock do not need to be used as context managers. The mocker fixture automatically undoes mocking at the end of a test. This warning can be ignored if it was triggered by mocking a context manager. https://pytest-mock.readthedocs.io/en/latest/remarks.html#usage-as-context-manager
with mocker.patch("dvclive.live.get_dvc_repo", return_value=None):
```
& 
```
/dvclive/tests/test_main.py:229: PytestWarning: Value of environment variable DVCLIVE_RESUME type should be str, but got True (type: bool); converted to str implicitly
monkeypatch.setenv(env.DVCLIVE_RESUME, True)
```
<details> …

pytest: fix mocker as context manager and setenv test warnings

---

src/dvclive/live.py
tests/test_dvc.py

guide.
Will close https://github.com/iterative/dvclive/issues/670 (requires https://github.com/iterative/dvc/pull/9879)
- Generates a warning message when dvclive is init'ed inside a `dvc repro` pipeline stage (but not when inside `dvc exp run`)
With https://github.com/iterative/lstm_seq2seq:
```
$ dvc repro
Running stage 'download':
...
Running stage 'train':
> python train.py
Number of samples: 10000
Number of unique input tokens: 72
Number of unique output tokens: 101
Max sequence length for inputs: 117
Max sequence length for outputs: 149
WARNING:dvclive:Some DVCLive features are unsupported in `dvc repro`.
To use DVCLive with a DVC Pipeline, run it with `dvc exp run`.
GPU available: True (mps), used: True …
```

live: warn when DVC_ROOT is set but DVC_EXP_BASELINE_REV is not

---

pyproject.toml
src/dvclive/live.py

The function we were using from `dvc.repo.artifacts` was dropped in https://github.com/iterative/dvc/pull/9770
deps: bump  "dvc>=3.22.1"
deps: Add `gto`

log_artifact: Use name validation from GTO.

---

src/dvclive/live.py
tests/test_dvc.py
tests/test_log_artifact.py
tests/test_post_to_studio.py

Before `DVC_ROOT`, we often checked for whether dvclive was running inside `dvc exp run` because we had no way to check whether running inside `dvc repro`, but often we really want the same behavior in both scenarios. This PR expands the use of `DVC_ROOT` to check whether dvclive is running inside a pipeline.

Use `DVC_ROOT` to detect pipeline

---

.pre-commit-config.yaml
examples/DVCLive-HuggingFace.ipynb

Per https://github.com/iterative/dvclive/pull/723#issuecomment-1766175609, codespell may have issues checking jupyter notebooks. It did catch one valid issue, but I think dealing with false positives for ipynb files makes it not worth it.

codespell: disable for .ipynb files

---

examples/DVCLive-Evidently.ipynb
src/dvclive/dvc.py
src/dvclive/lightning.py
src/dvclive/live.py
tests/test_dvc.py
tests/test_post_to_studio.py

custom exp name

---

pyproject.toml
src/dvclive/lightning.py
tests/frameworks/test_lightning.py

Fixes #726 
Update lightning logger kwargs to reflect dvclive 3.0 updates and other missed changes

Lightning 3.0 updates

---

src/dvclive/live.py
tests/frameworks/test_lightning.py
tests/test_dvc.py
tests/test_log_artifact.py
tests/test_make_dvcyaml.py

Instead of defaulting to the git root for dvc.yaml, use the current path. This is technically a breaking change, but it simplifies the dvc.yaml logic and should have the same behavior for most users.
Rationale for this change:
* Avoids unnecessary git logic that can cause [unexpected behavior](https://iterativeai.slack.com/archives/C03JS2V4MQU/p1698052870762279)
* More consistent with dvc commands (for example, `dvc stage add` writes `dvc.yaml` in the current directory, not the git root)
* Simpler code

dvcyaml: write to cwd instead of git root

---

src/dvclive/live.py
tests/test_post_to_studio.py

Before we only post the `done` event during `live.end()`, which doesn't include any data. We should also be posting a `data` event before that to make sure the latest data is also sent.

post data to studio on end

---

src/dvclive/error.py
src/dvclive/live.py
tests/test_log_param.py

Before this PR, when logging an invalid parameter type, you would always get a generic error message that doesn't reflect the actual type passed:
```python
>>> Live().log_param("p", pd.DataFrame())
...
dvclive.error.InvalidParameterTypeError: Parameter type <class 'tuple'> is not supported.
```
With this PR, you get info about the actual invalid type passed:
```python
>>> Live().log_param("p", pd.DataFrame())
...
dvclive.error.InvalidParameterTypeError: cannot represent an object: Empty DataFrame
```
This happens because `log_params` dumps a dict to yaml and the error comes from failing to write to yaml. Unfortunately, I don't see an easy way to parse the error output to get more control over the message.

log_params: fix invalid type msg

---

pyproject.toml

guide.
------
Related to https://github.com/iterative/dvc/issues/9940
~Required for testing `studio`/`vscode-dvc` as the version of `dvc-render` is conflicted between `dvc` and `dvclive`.~
Needed to resolve dependency conflicts in Studio.

`plots`: standardise across DVC/Studio/VS Code (update dependencies)

---

pyproject.toml
src/dvclive/live.py
src/dvclive/utils.py
tests/test_utils.py

This PR is a part of this issue: https://github.com/iterative/dvclive/issues/750 
Changes: 
- add support for Add support for DataFrames and Numpy Arrays in `log_plot()` 
- implemented a new function for convert datapoints to List[Dict] `dvclive/utils.py/convert_datapoints_to_list_of_dicts` 
- added new Python dependencies: `pandas` and `numpy`
- added a new argument to the `log_plot()`: `columns: Optional[List[str]] = None,` - optional list of column names for data in Numpy Array format
JN to test new feature: [log_plots.ipynb](https://drive.google.com/file/d/1tDoigZrpo_YzPiS-fXsrDHSJuSmgM-uT/view?usp=sharing)
guide.

Add support for DataFrames and Numpy Arrays for log_plot()

---

src/dvclive/live.py
tests/test_resume.py

Dvclive was not preserving summary metrics when `resume=True`.

preserve summary metrics on resume

---

pyproject.toml
src/dvclive/live.py
tests/test_step.py

https://github.com/iterative/dvclive/pull/749 introduced a bug where `live.end()` could throw a key error on `live.summary["end"]`. 
Found thanks to downstream failures in huggingface accelerate tests: https://github.com/huggingface/accelerate/pull/2279. See an example of the failure in https://github.com/huggingface/accelerate/actions/runs/7300196833/job/19894391020.

end: bug fix for step

---

src/dvclive/live.py
tests/test_log_artifact.py

guide.
Closes #761 by explicitly calling `builtins.type` instead of the `type` argument that's shadowing it.

Fix `TypeError` by explictly calling shadowed `builtins.type`

---

src/dvclive/live.py
src/dvclive/studio.py
src/dvclive/utils.py

add typehints to Live's public methods

---

src/dvclive/error.py
src/dvclive/live.py
src/dvclive/plots/image.py
tests/plots/test_image.py

This pull request makes it so:
- If `live.log_image` is called without image format in the `name`, we will try to infer the format from the image
- If we could not infer the format, we will raise an error message early in `could_log` instead of falling through to `PIL.Image.save`
Closes #743 
@dberenbaum, I felt that both approaches need to be implemented together. Inferring the format is nice, but only works in _some_ situations and not others. So for a situation where the format could not be inferred, I added an additional check that will fail early and won't attempt saving the image.
My Python must be _not optimal_. The changes are split into two commits, feature-wise. 
- I've also added unit tests for the behavior.
- Behavior change: in `could_log` I suggest we take `name` and `val`, …

fix: Improve safety of logging images with implicit formats

---

src/dvclive/live.py

This PR fix this issue: https://github.com/iterative/dvclive/issues/755
I was inspired by the dvc.org documentation for most arguments and descriptions. Let me know if you were hoping for something more technical. 
I'm still struggling to find a nice description for `cache`, `post_to_studio` and `save_dvc_exp`. If you could enlighten me so I can finish this MR, that would be great. 
I notice some missing type hints in the methods. I would love to correct those, but I'll do it on another PR.

Add docstrings to public functions

---

.github/workflows/tests.yml
CONTRIBUTING.rst
noxfile.py
pyproject.toml

-----
Follow up to https://github.com/iterative/dvc/pull/10265. DVCLive can no longer support Python 3.8 as it depends on DVC and DVC dropped support in the aforementioned PR.

drop Python 3.8 support

---

src/dvclive/live.py

Missed [this failure](https://github.com/iterative/dvclive/actions/runs/7901186125/job/21564257619) in #783.

revert dropping of noqa

---

tests/frameworks/test_lightning.py
tests/test_post_to_studio.py

Adds a test for #788. I don't think we need to make a test specific to lightning or threads. The underlying problem is that if dvclive sent plots to studio multiple times with the same step value, only the first value would get sent to studio. Added a test here for that, which fails on main and passes in #788.

Test studio counter

---

pyproject.toml
src/dvclive/live.py
src/dvclive/studio.py
tests/conftest.py
tests/test_post_to_studio.py

----
Part of https://github.com/iterative/studio/issues/8848
Repeat of https://github.com/iterative/dvclive/pull/779 but stripped back to only send subdir. 
Depends on https://github.com/iterative/dvc-studio-client/pull/154 / https://github.com/iterative/studio/pull/9173 /https://github.com/iterative/dvc/pull/10303

studio: add subdir to live metrics post messages to support live experiments in monorepos

---

src/dvclive/lightning.py
src/dvclive/live.py
src/dvclive/studio.py
tests/frameworks/test_lightning.py
tests/test_post_to_studio.py

Following a bug detected during [this feature](https://github.com/iterative/dvclive/pull/773) development.
Using the `step` value to send the latest data to Studio can lead to weird behavior because the `step` is poorly defined in some loggers (eg. pytorch lightning logger). Because the step definition is poorly defined in lightning we used a hack to ensure the `log_metrics` calls by the lightning trainer were correct. But calling `log_metrics` from outside the lightning trainer (a separate thread for instance) leads to data not being sent to Studio or duplicates data. 
This PR introduces a counter for each metric that increments when Studio receives the data points. Instead of using the `step` property as a proxy for which data has been sent to studio, we literally count them now. This …

Add internal counters to send only the latest datapoints to studio

---

pyproject.toml
src/dvclive/live.py
src/dvclive/studio.py
tests/test_post_to_studio.py

Follow up to https://github.com/iterative/dvc/pull/10345
TODO:

use dvc_exp_git_remote to set studio repo url

---

src/dvclive/live.py
src/dvclive/studio.py
tests/test_post_to_studio.py

Closes https://github.com/iterative/studio-support/issues/95

post to studio in thread to avoid blocking

---

src/dvclive/live.py
tests/plots/test_sklearn.py

Fixes #812

---

tests/frameworks/test_lightning.py

Caused by https://github.com/iterative/dvclive/actions/runs/8872661976/attempts/1
Decision to drop the test: https://github.com/iterative/dvclive/pull/816#issuecomment-2083668012

Drop outdated flakey lightning test

---

src/dvclive/live.py
tests/test_post_to_studio.py

W/o this fix in the `example-get-started-experiments` we are not getting images published to Studio (it doesn't have time to complete, `evaluate` exits faster).
--------------

fix(studio): wait for studio metrics publish to complete on end

---

pyproject.toml
tests/frameworks/test_huggingface.py

@shcheklein Added a couple minor changes to your PR

make hf tests work

---

src/dvclive/live.py
src/dvclive/plots/custom.py
tests/plots/test_custom.py

support lists for log_plot y val

---

src/dvclive/plots/custom.py
tests/plots/test_custom.py

Fixes #10482 (report in dvc repo) at https://github.com/iterative/dvc/issues/10482

Fix: Empty string as template in CustomPlot.init

---

src/dvclive/live.py
tests/test_make_dvcyaml.py

Support `pathlib.Path` values for `dvcyaml` argument in `Live()`.

---

src/dvclive/monitor_system.py

This happens on line :132 in case of handled exception in the first iteration of the loop.

Fix local variable 'last_metrics' referenced before assignment

---

src/dvclive/live.py
src/dvclive/studio.py
tests/test_post_to_studio.py

Fixes root cause of the #858. We'll still need another fix / research on why it was hanging.
There was a race condition since both (main and Studio updates) threads were reading / updating the same `live` instance values simultaneously.
It seems it might be happening if a training loop is faster then Studio API call (can be when we have a lot of images).
----------------------------------

fix(studio): package data to send in main thread

---

src/dvclive/live.py
tests/test_post_to_studio.py

Continuation of https://github.com/iterative/dvclive/pull/860
Fixes #858 
We catch properly unexpected exceptions in Studio updates thread and continue consuming from the queue (to make it empty so `join` below doesn't hang). 
--------------------

fix(studio): handle unexpected exceptions in updates thread
